title = "Письма с войны"
languageCode = "ru"
defaultContentLanguage = "ru"

[taxonomies]
  tag   =  "tags"
  author = "authors"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "О нас"
    url = "/about"
    weight = 20

  [[menu.main]]
    identifier = "posts"
    name = "Публикации"
    url = "/posts"
    weight = 30

[outputs]
home = ["HTML", "RSS", "JSON"]

[module]
  [[module.mounts]]
    excludeFiles = 'admin/*'
    source = 'static'
    target = 'static'
